### PR TITLE
When respawned, clear all Memory

### PR DESCRIPTION
**Pull request by pieterbrandsen**

### CODE REVIEW

**Comment by khoover** [comment]
Doesn't this also erase memory if all creeps are dead after a respawn?

**Comment by pieterbrandsen** [comment]
No, only first tick is possible thanks to this check: `room.controller.safeMode !== SAFE_MODE_DURATION - 1`. Only if the safeMode isnt 19999 it returns false

@khoover

**Comment by khoover** [comment]
I suppose there's some edge case where you go into safe mode again, and all
your creeps are dead, etc., but that seems incredibly unlikely.

**Comment by pieterbrandsen** [comment]
The controllerLevel 1, room count 1, creep count 1 check fix that

**Pull request merged**
