### PR TITLE
Complier compliance & BandAid fix for operator.ts

### PR DESCRIPTION
**Pull request by realacesu**
Changed all constants/general imports to use relative importing to file importing it

Changed constants/general.ts and commented a non power task. if we take this approach _**ALL**_ tasks must have all task function declarations in the role files. Going forward, add these and maybe error with not implemented and creep debug info to see what called it because it shouldn't be called. This is generally avoided because creeps individually select tasks and are not assigned. We will likely never see this.

### CODE REVIEW

**Comment by realacesu** [comment]
oops added notmycreeps.invader, this addition doesn't break anything as it still passes invaders to enemy

**Comment by CarsonBurke** [comment]
I like idea of notMyCreeps including invaders :)

**Comment by CarsonBurke** [comment]
I'm experiencing zero issues with constants on the unstable branch without using this PR. What is the reason behind the relative imports?

I like the invader thing. Could you make a separate PR for that please? I will happily merge that ASAP

**Comment by realacesu** [comment]
> I'm experiencing zero issues with constants on the unstable branch without using this PR. What is the reason behind the relative imports?

On node 16.20.2, and 20.10.0 This was occurring for me, with no changes to the unstable branch

**Comment by realacesu** [comment]
Adding relative imports took away the require that was present on the top of the file after the banner

**Comment by CarsonBurke** [comment]
> Adding relative imports took away the require that was present on the top of the file after the banner

Which file and which banner? sorry.

**Comment by CarsonBurke** [comment]
> > I'm experiencing zero issues with constants on the unstable branch without using this PR. What is the reason behind the relative imports?
> 
> On node 16.20.2, and 20.10.0 This was occurring for me, with no changes to the unstable branch

v16.17.1, no issues for me

**Comment by realacesu** [comment]
> > Adding relative imports took away the require that was present on the top of the file after the banner
> 
> Which file and which banner? sorry.

Build output. Complied main.js output

Banner comes from rollup cfg

**Comment by realacesu** [comment]
Node v16.17.1 same issue without PR. Unsure why its doing this

**Pull request merged**
