### PR TITLE
#662: score rampart repair targets somewhat based on damage received last tick

### PR DESCRIPTION
**Pull request by pieterbrandsen**

### CODE REVIEW

**Comment by pieterbrandsen** [comment]
@CarsonBurke Please review code

I added properties to rampart prototype.

When threat appears it starts tracking damage, when it goes away all store gets removed

I save the start hits, when below start hits it gets priotized as removed hits count double for towers and triple for creeps

**Comment by CarsonBurke** [comment]
I like that this code does a great job trying to accomplish what its goal is. However there are two main issues

1. I don't believe this code works. Considering properties on things like ramparts persist state only intra-tick, this data will probably not be accurately describing the damage taken last tick
2. We need the last x ticks, not just last tick. Just as you have a single-value moving average for stats like cpu usage, energy income, etc. we need a stat for how much damage the rampart has taken over the last few ticks

Does this make sense?

**Review by CarsonBurke — CHANGES_REQUESTED** [review]
See previous comment

**Comment by CarsonBurke** [comment]
Looks much better! I'm going to make a couple of changes to ensure it works more efficiently and normally

**Comment by CarsonBurke** [comment]
@pieterbrandsen I'm going to remake this using global. There is a lot of redeemable stuff here, but there are a few fundamental things I'm going to change to make things a bit easier to use and a bit cheaper to run

**Pull request closed without merging**
